### ISSUE TITLE
Build.Changes.Change is null

### ISSUE THREAD

**Issue by AdamFrisby** [mavezeau/TeamCitySharp#18]
This is on version 2.0.0-beta1 via NuGet.

Demo code - .NET Core 2.2

Accessing via: 
var build = tcc.Builds.ById(buildIntID);
var buildChanges = build.Changes;

From here, trying to get the Change list returns a null List. i.e.
buildChanges.Change == null

**Comment by mavezeau** [comment]
Hi Sorry, sorry for the delay. 

It's not a real bug because we have received all datas from teamcity. In this case,  for Changes and Statistics, we will received only the href... Without any data. 

Ex: 
http://server/httpAuth/app/rest/builds/id:8628185

We received this data:

`
<build id="8628185" buildTypeId="Testq" number="5500.63" status="SUCCESS" state="finished" href="/httpAuth/app/rest/builds/id:8628185" webUrl="http://server/viewLog.html?buildId=8628185&buildTypeId=test">
<statusText>Success</statusText>
<buildType id="test" name="test" description="" projectName="test" href="/httpAuth/app/rest/buildTypes/id:test" webUrl="http://server/viewType.html?buildTypeId=test"/>
<queuedDate>20181221T100959-0500</queuedDate>
<startDate>20181221T101012-0500</startDate>
<finishDate>20181221T101040-0500</finishDate>
<triggered type="user" date="20181221T100959-0500">
<user username="Foo" name="Foo" id="62" href="/httpAuth/app/rest/users/id:62"/>
</triggered>
<lastChanges count="1">
<change id="96529" version="5500" username="foo" date="20181221T100745-0500" href="/httpAuth/app/rest/changes/id:96529" webUrl="http://server/viewModification.html?modId=96529&personal=false"/>
</lastChanges>
<changes href="/httpAuth/app/rest/changes?locator=build:(id:8628185)"/>
<revisions count="1">
<revision version="5500">
<vcs-root-instance id="1068" vcs-root-id="VCS" name="VCS" href="/httpAuth/app/rest/vcs-root-instances/id:1068"/>
</revision>
</revisions>
<versionedSettingsRevision version="ff8611e8d107a313063407eff1bd36efa77ada77" vcsBranchName="refs/heads/master">
<vcs-root-instance id="1287" vcs-root-id="VCS2" name="td-teamcity-project-configuration" href="/httpAuth/app/rest/vcs-root-instances/id:1287"/>
</versionedSettingsRevision>
<agent id="297" name="Agent" typeId="149" href="/httpAuth/app/rest/agents/id:297"/>
<artifacts href="/httpAuth/app/rest/builds/id:8628185/artifacts/children/"/>
<relatedIssues href="/httpAuth/app/rest/builds/id:8628185/relatedIssues"/>
<properties count="1">
<property name="env.CHECKOUT_DIR" value="%system.teamcity.build.workingDir%" inherited="true"/>
</properties>
<statistics href="/httpAuth/app/rest/builds/id:8628185/statistics"/>
</build>
`


If you look on the xml, the Statistics and Changes didn't contain data,  only a href. Normally, the rest didn't taking a partial data but it's possible for me to return the href. 

But the real solution for you it's to use fields option. 

Example: 
`
ChangeField changeField = ChangeField.WithFields(true,version:true,username:true);
ChangesField changesField = ChangesField.WithFields(changeField: changeField);
BuildField buildField =  BuildField.WithFields(id:true, changes: changesField);
var build = m_teamcity.Builds.GetFields(buildField.ToString()).ById("8628185");

var buildChanges = build.Changes;
`
I will check if we have multiple entities with the same issue.  I will kept this bug open only for a remember for me

**Comment by mavezeau** [comment]
Added to 2.0.1
