### ISSUE TITLE
Is this project active ?

### ISSUE THREAD

**Issue by DevTown** [mavezeau/TeamCitySharp#37]
Hi i am wondering if this project is activ or not?
Is this the code for the released version on nuget ? 
I have problems to compile this sources because of missinmg "," and ";". 
So if there is anny active developing here ? 
I would like to generate some PR´s for upgrading and extending this project.

**Comment by mavezeau** [comment]
The project is always alive but without many update because the rest api of teamcity are stable. 

Yes the latest version was located here: https://www.nuget.org/packages/TeamCitySharp-forked-mavezeau/

Im not sure to understand what do you talk with about missing ',' and ';"

if you would like to contribute to this project no problem if is not specific and your fix are generic its perfect

**Comment by DevTown** [comment]
THX for the quick reply. 
Now that I know there is an active project I can get on with the upgrades ;-) 

As for the missing , and ; -> in the file Locators/BuildLocators.cs in line 45 my studio is missing a "," and in the same file where are also missing ";" in line 109,142,145,148 ... 
I was just wondering if I have a corrupted checkout/fork or something like that.

**Comment by DevTown** [comment]
OK i think the PR #36 is missing.

**Comment by UlyssesWu** [comment]
If you'd like to utilize `async` / `await`, you can try my fork [here](https://github.com/UlyssesWu/TeamCitySharp)

**Comment by mavezeau** [comment]
Yes I fix the issue from  #36 this morning and I generated a new version in nuget.
