### ISSUE TITLE
Unable to see a method to access Administration Section and My Settings and Tool via RestAPI

### ISSUE THREAD

**Issue by satyaprakashv** [mavezeau/TeamCitySharp#6]
Hi Mavezeau,

I do not see any method to access/update admin sections via REST API Call using TeamCitySharp.
I need to setup SMTP configuration and also Add Email Notification through my custom application where I uses TeamCitySharp liabrary for creating TC projects and Builds.

Is there any possibility? any idea?

**Comment by mavezeau** [comment]
Hi Satyaprakashv,

Some part of administration was not accessible with REST API (Not open by teamcity).Their have some bugs for this. But I think it's possible but curl directly. 

Please check all call possible from the swagger generation. 

https://dploeger.github.io/teamcity-rest-api/

But I'm not sure to understand your request because normally the smtp server did not change dynamically. 

I don't know if it's working but the configuration of email is written to xml file.   Go to Teamcity Data folder and the path "config\_notifications\email\email.config.xml"

Regards,

**Comment by satyaprakashv** [comment]
Hey Mavezeau,

Actualy I have created a utility that helps to configure the a Devops pipeline to build and deploy steps in any teamcity instance without login into teamcity (No need any knowledge of TC like, just need URL and credentials), so I just wanted to add feature like setting build failure notification through this utility for that I need to access the Admin sections to set emails notifications.
make sense?

Regards
Satya

**Comment by mavezeau** [comment]
Yes probably, but without modify / generate the config file I think is impossible for now

**Comment by satyaprakashv** [comment]
Hey Marc,

I just got another idea to use the PS script and add a build step to send emails.  but need to see how can I execute this build step if any of the build step fail in any build configuration under the TC Project.

Any idea will be much appreciated..

Thanks
Satya

**Comment by mavezeau** [comment]
Hi Satya, 

It's not the roles on this library to notify the user. This is your business case only, but they exist multiple library C# for this... example this one https://github.com/gavynriebau/System.Net.Mail.Abstractions  

Sorry for the delay (Vacation times)
Regrads,
